### ISSUE TITLE
oracle-javaX-installer não funciona mais

### ISSUE THREAD

**Issue by t-bonatti** [caarlos0/ansible-role-java-dev#2]
Desde que a oracle moveu seus JDK para a página de `archive` parou de funcionar isso:

https://github.com/caarlos0/ansible-role-java-dev/blob/master/tasks/main_Ubuntu.yml#L4

Pesquisando na internet achei uma solução manual por enquanto:

http://www.webupd8.org/2017/06/why-oracle-java-7-and-6-installers-no.html

@caarlos0 O que acha? Será que tem alguma solução automática?

**Comment by caarlos0** [comment]
removi o jdk7, o 8 teoricamente funciona...

 https://github.com/caarlos0/ansible-role-java-dev/commit/01023876bc2b26b99cd9aa001d86f1ac3852df3e

**Comment by t-bonatti** [comment]
Não, pois está usando o `jdk-8u111` que não é o ultimo, e também foi movido =/

**Comment by t-bonatti** [comment]
E precisamos do JDK7 para o ContaAzul

**Comment by caarlos0** [comment]
> E precisamos do JDK7 para o ContaAzul

esse repo nao é da contaazul :)

**Comment by caarlos0** [comment]
o jdk 7 nao tem mais pacotes pq foi movido pra archive... removi a instalacao do jdk7...

quem quiser, vai ter que instalar na mao, nao tem outro jeito por hora afaik.
